global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'solicitor-brain-alerts'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      repeat_interval: 15m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 4h

receivers:
  - name: 'solicitor-brain-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/api/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/api/alerts/critical'
        send_resolved: true
    # Add email configuration here if needed
    # email_configs:
    #   - to: 'alerts@firm.co.uk'
    #     from: 'solicitor-brain@firm.co.uk'
    #     smarthost: 'smtp.example.com:587'
    #     auth_username: 'username'
    #     auth_password: 'password'

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/api/alerts/warning'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']