global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'solicitor-brain'

rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # Solicitor Brain API
  - job_name: 'solicitor-brain-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'

  # ROCm GPU metrics (if available)
  - job_name: 'rocm-gpu'
    static_configs:
      - targets: ['rocm_smi_exporter:9101']
    honor_labels: true

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:6379']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']